import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#c3f400",
        "on-secondary-container": "#00686f",
        "error-container": "#93000a",
        surface: "#10131a",
        "surface-dim": "#10131a",
        "on-background": "#e1e2eb",
        primary: "#ffffff",
        "surface-container-low": "#19131a",
        "surface-container-high": "#272a31",
        "on-surface": "#e1e2eb",
        "tertiary-container": "#ffd7f0",
        "on-error": "#690005",
        "surface-container-highest": "#32353c",
        "outline-variant": "#444933",
        "secondary-container": "#00eefc",
        "tertiary-fixed-dim": "#fface8",
        tertiary: "#ffffff",
        "on-secondary": "#00363a",
        "inverse-primary": "#506600",
        "primary-container": "#c3f400",
        "on-primary-container": "#556d00",
        background: "#10131a",
        "inverse-on-surface": "#2e3037",
        outline: "#8e9379",
        "on-tertiary": "#5e0053",
        "on-primary": "#283500",
        "on-primary-fixed": "#161e00",
        "surface-tint": "#abd600",
        error: "#ffb4ab",
        "on-secondary-fixed": "#002022",
        "on-surface-variant": "#c4c9ac",
        "on-tertiary-fixed-variant": "#840076",
        "secondary-fixed": "#7df4ff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#004f54",
        "surface-bright": "#363940",
        "surface-container": "#1d2026",
        "on-primary-fixed-variant": "#3c4d00",
        "secondary-fixed-dim": "#00dbe9",
        "on-tertiary-fixed": "#3a0033",
        "tertiary-fixed": "#ffd7f0",
        "inverse-surface": "#e1e2eb",
        "primary-fixed-dim": "#abd600",
        "surface-container-lowest": "#0b0e14",
        secondary: "#d3fbff",
        "on-tertiary-container": "#b700a4",
        "surface-variant": "#32353c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "grid-size": "32px",
        "margin-mobile": "16px",
        gutter: "24px",
        unit: "4px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-mono": ["14px", { lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
